[package]
name = "usermgmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.10", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
confy = "0.4.0"
tempfile = "3.3.0"
rpassword = "6.0"
# ldap3 = { version = "0.10.3" }
# maplit = "1.0.2"